### ISSUE TITLE
Issue to Access "HPFI_Version_Check.txt" when running script with the help of mass deployment software

### ISSUE THREAD

**Issue by JiPa2022** [ofelman/DockUpdater#3]
Hi, Iam trying to run this script through Baramundi to mass deploy it but there seems to be an issue while creating "HPFI_Version_Check.txt"

```
Get-Content : Der Pfad "C:\HP_Update\HPFI_Version_Check.txt" kann nicht gefunden werden, da er nicht vorhanden ist.
In C:\HP_Update\DockUpdater10016.ps1:131 Zeichen:17
+     $TestInfo = Get-Content -Path $pCheckFile
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\HP_Update\HPFI_Version_Check.txt:String) [Get-Content], ItemNotFound
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
In C:\HP_Update\DockUpdater10016.ps1:137 Zeichen:9
+         $InstalledVersion = $InstalledVersion.Split(":") | Select-Obj ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

It will have something to do with the way access privileges or variables are working in the baramundi invoked session, but I can´t get around it. - Any ideas? - if I run it manually on the same machine, everything works.

**Comment by JiPa2022** [comment]
I´ve found something which might point to the issue and also allow me to create (at least a local) fix.

The issue seem to originate from line 290 where you call "HPFirmwareInstaller.exe" -

```
 Write-Host " Running HP Firmware Check... please, wait" -ForegroundColor Magenta
        Try {
            $Error.Clear()
            $HPFirmwareTest = Start-Process -FilePath "$OutFilePath\$SPNumber\HPFirmwareInstaller.exe" -ArgumentList "-C" -PassThru -Wait -NoNewWindow
```

this process seem to be responsible for the creation of "HPFI_Version_Check.txt" - now for some (for me unknown) reason, you need to differentiate between Dock versions.

This is visible in 296-300

```
        if ( $Dock.Dock_Attached -eq 9 ) {  # Essential dock found - must handle uniquely
            $VersionFile = "$OutFilePath\$SPNumber\HPFI_Version_Check.txt"
        } else {
            $VersionFile = "$PSScriptRoot\HPFI_Version_Check.txt"
        }
```

Open question about the EXE here is, why does the TXT file get written into different folder if the Dock is a specific version, this doesn´t make any sense to me, should it even matter which Dock Model it is, to decide in which path the log file is written?

But back to the script, now in my case when I run the file manually and locally it actually seem to put the file in "$PSScriptRoot" which means, the file is not written to the root folder of "HPFirmwareInstaller.exe" but to the root folder of the PS Script itself.

The problem is, that I had no file created in either path, when the PS Script was triggered by the BMA (Baramundi Management Agent) - at the same time I got no errors apart from the one mentioned in the first post, so the file probably got written "somewhere" successfully. So I searched a bit and found this:
 
![bma_script](https://github.com/ofelman/DockUpdater/assets/111439373/d1acb09a-c147-4ade-aafb-63a96e47e4e3)

This tells me that "HPFirmwareInstaller.exe" probably access some environment variables for the Logfile Path which change when the PS Script is run by BMA

I will probably be able to fix this for my purpose by just hardcoding the path into the script but its only a workaround at this point. I also did post this issue in Baramundi Forum

**Comment by JiPa2022** [comment]
Ok, I think I found a valid fix suitable for any environment. (no guarantee / use at Your own risk)

The problem seems to be, that "HPFirmwareInstaller.exe" seems to refer to "current directory" to output the Textfile in case the Dock is "essential" (I still don´t know why the program handles it like that but lets work with it)

The crucial part of the code in the PS script

`            $HPFirmwareTest = Start-Process -FilePath "$OutFilePath\$SPNumber\HPFirmwareInstaller.exe" -ArgumentList "-C" -PassThru -Wait -NoNewWindow`

AND

`        if ( $Dock.Dock_Attached -eq 9 ) {  # Essential dock found - must handle uniquely
            $VersionFile = "$OutFilePath\$SPNumber\HPFI_Version_Check.txt"
        } else {
            $VersionFile = "$PSScriptRoot\HPFI_Version_Check.txt"
        }
`

The fix (after line 62):

`Set-Location $PSScriptRoot`

Conclusion:
The issue is, that once ran by BMA the environment variable $PWD (Current Directory) is the Path to the BMA Agent Directory for some reason and not the PS Script as you would expect it when ran manually. (or probably even when ran by Windows own tools like Taskplanner etc. (not tested though)

Since "HPFirmwareInstaller.exe" seems to refer to this variable upon creating the textfile it creates an issue as soon as you expect the file to be in "$PSScriptRoot" (which it normally would be, if ran manually)

So with "Set-Location $PSScriptRoot" you "force" "HPFirmwareInstaller.exe" to put the Text File in the Root Directory of the PS Script as expected in the rest of the code.

**Comment by ofelman** [comment]
the reason for the output txt file being in different places is that docks updater writes them in different places... my script adjusts the path to query the output txt file based on the dock that was detected and the tool used
